In [4]:
import numpy as np
a = [1,2,3,4,5]
b = [2,3,4,5,6]
ary = []
for i in range(0, len(a)):
    ary.append(a[i] + b[i])
print ary
print type(ary)


[3, 5, 7, 9, 11]
<type 'list'>


In [5]:
a = np.array([0,1,2,3,4,5])
print type(a)
print a, a.ndim, a.shape

<type 'numpy.ndarray'>
[0 1 2 3 4 5] 1 (6L,)


In [10]:
a = np.array([0,1,2,3,4,5])
b = np.array([2,3,4,5,6,7])
print a+b
print a-b
print a*b
print a * 1.0 /b

[ 2  4  6  8 10 12]
[-2 -2 -2 -2 -2 -2]
[ 0  3  8 15 24 35]
[ 0.          0.33333333  0.5         0.6         0.66666667  0.71428571]


In [11]:
a = np.array([0,1,2,3,4,5])
b = a.reshape((3,2))
print b, b.ndim, b.shape

[[0 1]
 [2 3]
 [4 5]] 2 (3L, 2L)


In [16]:
print b
print b[1][0]
#= 77
b[1][0] = 77
print b
print b
print a


[[ 0  1]
 [77  3]
 [ 4  5]]
77
[[ 0  1]
 [77  3]
 [ 4  5]]
[[ 0  1]
 [77  3]
 [ 4  5]]
[ 0  1 77  3  4  5]


In [18]:
a = np.array([0,1,2,3,4,5])
c = a.reshape((3,2)).copy()
print c
c[0][0] = -99
print a
print c


[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]
[[-99   1]
 [  2   3]
 [  4   5]]


In [19]:
a = np.array([0,1,2,3,4,5])
print a *2
print a **2

b = [1,2,3,4,5]
print b * 2
print b ** 2


[ 0  2  4  6  8 10]
[ 0  1  4  9 16 25]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
a = np.array([0,1,2,3,4,5])
print a[np.array([2,3,4])] # filter value by position 

print a > 4
print a[a>4] # filter value by logic 
a[a>4] = 4
print a

print a
print a.clip(0,3)
print a.clip(1,3)
#help(a.clip)


[2 3 4]
[False False False False False  True]
[5]
[0 1 2 3 4 4]
[0 1 2 3 4 4]
[0 1 2 3 3 3]
[1 1 2 3 3 3]


In [30]:
c = np.array([1,2,np.NAN, 3, 4])
print c
print np.isnan(c)
print c[-np.isnan(c)]
print np.mean(c[-np.isnan(c)])

[  1.   2.  nan   3.   4.]
[False False  True False False]
[ 1.  2.  3.  4.]
2.5


C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.


In [31]:
np.array([1,"string"])
np.array([1,"string", set([1,2,3])])


array([1, 'string', set([1, 2, 3])], dtype=object)